# Generated by Django 5.2 on 2025-04-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('Repair', 'Repair'), ('Service', 'Service'), ('Mod', 'Modification'), ('Accessory', 'Accessory')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('synth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='my_app.synth')),
            ],
        ),
    ]
